"""`docs/judge-calibration.md`, generated from the stored labels and verdicts (PLAN.md B10.3).

The document is written by this function and not by hand, for the reason Part A's monthly
report is: a number that is typed into a document is a number that can be typed wrongly, and
one that is generated from the record can be regenerated by a stranger.
"""

from __future__ import annotations

import math

from drift.analysis.stats import Estimate
from gate.gold import TASKS
from gate.judge.calibration import KAPPA_FLOOR, Calibration, CorrectedRate, TaskCalibration


def _stat(e: Estimate, *, pct: bool) -> str:
    if e.n == 0 or math.isnan(e.point):
        return "no answer"
    if pct:
        return e.compact()
    if math.isnan(e.lo):
        return f"{e.point:.3f} (no interval)"
    return f"{e.point:.3f} ({e.lo:.3f} to {e.hi:.3f})"


def render_task(t: TaskCalibration) -> str:
    rows = [
        f"| Agreement with the human, raw | {t.raw_agreement:.1%} |",
        f"| Cohen's kappa | {_stat(t.kappa, pct=False)} |",
        f"| Krippendorff's alpha | {_stat(t.alpha, pct=False)} |",
        f"| Sensitivity (human yes, judge yes) | {_stat(t.sensitivity, pct=True)} |",
        f"| Specificity (human no, judge no) | {_stat(t.specificity, pct=True)} |",
        f"| The human said yes | {_stat(t.human_rate, pct=True)} |",
        f"| The judge said yes | {_stat(t.judge_rate, pct=True)} |",
    ]
    verdict = (
        f"**Usable** for this task: kappa is at or above {KAPPA_FLOOR}."
        if t.usable
        else f"**Refused** for this task: kappa is below {KAPPA_FLOOR}. The gate falls back to a "
        'programmatic grader or to "needs human review" (B2.3).'
    )
    out = [
        f"### {t.judge_key}, {t.task}",
        "",
        "| | |",
        "|---|---|",
        *rows,
        "",
        f"n = {t.counts.n} instances"
        + (f", {t.ungradeable} ungradeable and therefore absent" if t.ungradeable else "")
        + ".",
        "",
        f"The 2x2 table: {t.counts.true_positive} both yes, {t.counts.true_negative} both no, "
        f"{t.counts.false_positive} the judge said yes and the human said no, "
        f"{t.counts.false_negative} the reverse.",
        "",
        verdict,
    ]
    if not math.isnan(t.informative):
        out += [
            "",
            f"A judge that always answered with the majority class would agree "
            f"{max(t.human_rate.point, 1 - t.human_rate.point):.1%} of the time. This one agrees "
            f"{t.raw_agreement:.1%}, which is {t.informative:+.1%} on top of saying nothing.",
        ]
    if t.note:
        out += ["", f"Note: {t.note}."]
    return "\n".join(out)


def render_corrected(c: CorrectedRate, *, label: str) -> str:
    if c.degenerate:
        return f"- **{label}**: {c.describe()}."
    gap = c.corrected.point - c.apparent.point
    line = (
        f"- **{label}**: raw {c.apparent.compact()}, corrected {c.corrected.compact()}, "
        f"a move of {gap:+.1%}."
    )
    if c.clamped_share > 0.05:
        line += (
            f" {c.clamped_share:.0%} of resamples fell outside 0 to 1 and were clamped, so the "
            "interval is being shaped by the clamp as much as by the data."
        )
    return line


def render(calibration: Calibration, *, gold_instances: int, labelled: int) -> str:
    out = [
        "# Judge calibration",
        "",
        "Generated by `gate judge calibrate`. Every number here comes from "
        "`gate/gold/labels.jsonl` and `gate/gold/verdicts.jsonl` and can be regenerated offline.",
        "",
        f"Judge `{calibration.judge_key}`, rubric `{calibration.rubric_hash}`. "
        f"{labelled} of {gold_instances} gold instances labelled by hand.",
        "",
        "## Why this document exists",
        "",
        "An LLM judge that has not been calibrated is not a cheap measurement. It is a random "
        "number generator with good manners, and its output looks exactly like a real number. "
        "The figures below say whether this one is measuring anything, which way it fails, and "
        "what its scores mean once its own error is taken out of them.",
        "",
        "## Per task",
        "",
    ]
    out += [render_task(t) for t in calibration.tasks]

    usable = calibration.usable_tasks
    refused = calibration.refused_tasks
    out += [
        "",
        "## The decision",
        "",
        ("Usable for: " + ", ".join(usable) + "." if usable else "Usable for no task."),
        ("Refused for: " + ", ".join(refused) + "." if refused else "Refused for no task."),
    ]

    if calibration.self_agreement:
        out += [
            "",
            "## What it does when shown the same text twice",
            "",
            "Temperature 0, a two-word answer, and byte-for-byte the same prompt. Whatever the "
            "judge disagrees with itself about here, it cannot be measuring.",
            "",
            "| Task | Paired | Disagreements | Rate |",
            "|---|---:|---:|---|",
        ]
        for s in calibration.self_agreement:
            out.append(
                f"| {s.task} | {s.paired} | {s.disagreements} | "
                f"{s.rate.compact() if s.rate.n else 'not run'} |"
            )

    if calibration.position_bias:
        out += [
            "",
            "## Order bias",
            "",
            "The same case with the answer shown before the source instead of after it "
            "(PLAN.md B4). An absolute rubric should barely move; this is also the measurement "
            "that would condemn a pairwise preference judge, which B13 expects to fail.",
            "",
            "| Task | Paired | Moved | Yes only source-first | Yes only answer-first | McNemar p |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        for pb in calibration.position_bias:
            out.append(
                f"| {pb.task} | {pb.paired} | {pb.disagreements} | {pb.yes_only_first} | "
                f"{pb.yes_only_second} | {pb.mcnemar_p:.3f} |"
            )

    if calibration.verbosity:
        out += [
            "",
            "## Does length buy a better verdict?",
            "",
            'Within each human judgement separately, so "longer answers really are better" '
            "cannot masquerade as bias. The figure is the difference in median answer length "
            "between the answers the judge said yes to and the ones it said no to. An interval "
            "that crosses zero is no finding.",
            "",
            "| Task | Human said | Judge yes | Judge no | Median difference, characters |",
            "|---|---|---:|---:|---|",
        ]
        for v in calibration.verbosity:
            diff = (
                "no answer"
                if v.difference.n == 0 or math.isnan(v.difference.point)
                else f"{v.difference.point:+.0f} ({v.difference.lo:+.0f} to {v.difference.hi:+.0f})"
            )
            out.append(
                f"| {v.task} | {'yes' if v.human_label else 'no'} | {v.n_yes} | {v.n_no} | {diff} |"
            )

    out += [
        "",
        "## What these numbers do not say",
        "",
        "- The gold set is labelled by one rater. The intra-rater agreement from the second "
        "pass is the check on that, and it is published whatever it says; a second rater from "
        "outside work would be better and is sought.",
        "- Sensitivity and specificity are measured on this gold set, on this domain, under "
        "this rubric. A judge calibrated on financial-regulator guidance is not thereby "
        "calibrated on anything else, and the gate stores the rubric hash with every run so a "
        "figure can never be quoted against a rubric it was not measured under.",
        "- A corrected rate is only as good as the correction. Where sensitivity plus "
        "specificity is close to 1 the division is close to zero and the interval is wide; that "
        "is the arithmetic telling the truth, not a bug to be smoothed over.",
    ]
    return "\n".join(out) + "\n"


def render_summary(calibration: Calibration) -> str:
    """The short form, for the terminal."""
    lines = [f"judge {calibration.judge_key}, rubric {calibration.rubric_hash}"]
    for task in TASKS:
        t = calibration.task(task)
        lines.append("  " + t.describe())
        if t.note:
            lines.append(f"    note: {t.note}")
    return "\n".join(lines)
