"""The gold set: source documents, questions, answer instances, and human labels (PLAN.md B4).

The judge is an instrument, and an instrument is calibrated against something known. That
something is 300 answer instances, generated by three models of different sizes over 100
consumer questions about public financial-regulator guidance, each labelled by hand on two
binary judgements:

* **faithful**: every claim in the answer is supported by the source document.
* **complete**: the answer addresses the question that was asked.

Three models of different sizes on purpose. A gold set where every answer is good measures
nothing, because a judge that always says "fine" would score perfectly on it. The small model
is there to produce real failures.

Four files, all JSON lines, all append-only in the sense Part A means it:

    gate/gold/sources.jsonl     the regulator pages, with the bytes' hash and the date read
    gate/gold/questions.jsonl   100 questions, each naming the source it is answerable from
    gate/gold/instances.jsonl   300 answers, one per question per model
    gate/gold/labels.jsonl      Peter's judgements, appended one keypress at a time

**A label is a decision, not a copy of the answer.** It carries the instance id, the two
judgements and the hash of the text that was read. The text stays in `instances.jsonl`. If the
text ever changes, the hash stops matching and the label is dropped rather than trusted,
because the hash is the proof that the judgement is about the words in front of the reader.

**Labelling happens twice on a hundred of them.** `pass_no` is 1 or 2; the second pass, two
weeks later, is the intra-rater agreement that says whether the rater was consistent with
himself. A gold set with no such figure is a gold set that asks to be believed.
"""

from __future__ import annotations

import hashlib
import random
from collections.abc import Iterable, Iterator, Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# The two judgements. Named rather than positional everywhere, because "the first one" is how
# a faithfulness number ends up reported as a completeness number.
Task = Literal["faithful", "complete"]
TASKS: tuple[Task, ...] = ("faithful", "complete")

Publisher = Literal["fcac", "sec"]

SOURCES_FILE = "sources.jsonl"
QUESTIONS_FILE = "questions.jsonl"
INSTANCES_FILE = "instances.jsonl"
LABELS_FILE = "labels.jsonl"

# How many of the 300 are read a second time (PLAN.md B4). Fixed here rather than passed in,
# so the intra-rater sample is the same hundred every time the command is run.
INTRA_RATER_SAMPLE = 100
INTRA_RATER_SEED = 0

# A passage shorter than this is reported as thin by `gate gold status`. Not refused: the
# fetcher already refuses anything under 400 characters as an index page, and this is the
# softer line between "a document" and "a glossary stub with a site banner attached". A thin
# passage makes a poor faithfulness question, because there is barely anything in it to be
# unfaithful to, so the person writing the questions is told which ones they are.
THIN_PASSAGE_CHARS = 900


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def utc_now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


class SourceDoc(BaseModel):
    """One public page, stored as the text the model and the labeller both see.

    The text is committed, so a reader can check a label without fetching anything, and the
    hash and date say which bytes it was. Regulator pages are rewritten without notice; a
    faithfulness judgement made against today's wording is meaningless a year later unless the
    wording is kept.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str = Field(pattern=r"^(fcac|sec)-\d{3}$")
    publisher: Publisher
    title: str = Field(min_length=1)
    url: str = Field(min_length=1)
    retrieved_utc: str
    bytes_sha256: str  # of the fetched page, before extraction
    text: str = Field(min_length=1)  # the extracted passage the question is answerable from
    licence: str = Field(min_length=1)

    @property
    def text_sha256(self) -> str:
        return sha256_of(self.text)


class GoldQuestion(BaseModel):
    """A consumer question answerable from one source document, and what a complete answer
    has to contain. `must_mention` is the labelling aid, never shown to the model."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    id: str = Field(pattern=r"^q-\d{3}$")
    source_id: str = Field(min_length=1)
    question: str = Field(min_length=1)
    # The points a complete answer covers, written when the question was written and before
    # any model had answered it. Writing them afterwards would be writing the rubric to fit
    # the answers, which is how a completeness figure becomes a measure of nothing.
    must_mention: tuple[str, ...] = Field(min_length=1)
    # Set when the question cannot be answered from the source at all: the answer a faithful
    # model gives is "the document does not say". Every gold set needs some of these or a
    # judge that never catches an invented fact still scores well.
    unanswerable: bool = False


class AnswerInstance(BaseModel):
    """One model's answer to one question. The unit the judge judges and the human labels."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    # `i-` is an answer to the question's own document; `d-` is the distractor
    # stratum, where the question was served against a document that does not
    # support it. The served document is `source_id`, which is why that field
    # exists rather than being read off the question.
    id: str = Field(pattern=r"^[id]-\d{4}$")
    question_id: str
    source_id: str
    arm_key: str  # which model wrote it, by the panel's naming
    model_requested: str
    model_returned: str | None
    output: str
    output_sha256: str
    finish_reason: str | None
    generated_utc: str
    run_id: str
    ledger_id: int | None = None
    cost_usd: float | None = None

    @property
    def truncated(self) -> bool:
        return (self.finish_reason or "").lower() in {"max_tokens", "length"}


class GoldLabel(BaseModel):
    """One human judgement of one instance. Appended; never edited."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    instance_id: str
    faithful: bool
    complete: bool
    # Free text, for the cases the rubric did not foresee. Read when the rubric is revised.
    note: str = ""
    output_sha256: str
    pass_no: Literal[1, 2] = 1
    labelled_utc: str

    def value(self, task: Task) -> bool:
        return self.faithful if task == "faithful" else self.complete


def _read(path: Path, model: type[BaseModel]) -> Iterator[BaseModel]:
    if not path.is_file():
        return
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield model.model_validate_json(line)


def read_sources(path: Path) -> list[SourceDoc]:
    return [s for s in _read(path, SourceDoc) if isinstance(s, SourceDoc)]


def read_questions(path: Path) -> list[GoldQuestion]:
    return [q for q in _read(path, GoldQuestion) if isinstance(q, GoldQuestion)]


def read_instances(path: Path) -> list[AnswerInstance]:
    return [i for i in _read(path, AnswerInstance) if isinstance(i, AnswerInstance)]


def read_labels(path: Path) -> list[GoldLabel]:
    return [x for x in _read(path, GoldLabel) if isinstance(x, GoldLabel)]


def write_all(path: Path, records: Iterable[BaseModel]) -> None:
    """Write a whole file, for the generated ones (sources, questions, instances). Labels are
    never written this way; they are only ever appended."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as f:
        for r in records:
            f.write(r.model_dump_json() + "\n")
    tmp.replace(path)


def append_label(path: Path, label: GoldLabel) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8", newline="\n") as f:
        f.write(label.model_dump_json() + "\n")


def latest_labels(labels: Iterable[GoldLabel], *, pass_no: int = 1) -> dict[str, GoldLabel]:
    """The current judgement per instance for one pass: the last one appended wins, so a
    correction is a new line rather than an edit. Never merges the two passes, because the
    whole point of the second is to be compared with the first."""
    out: dict[str, GoldLabel] = {}
    for label in labels:
        if label.pass_no == pass_no:
            out[label.instance_id] = label
    return out


def usable_labels(
    labels: Mapping[str, GoldLabel], instances: Mapping[str, AnswerInstance]
) -> dict[str, GoldLabel]:
    """Labels whose instance still holds the text that was read. A label whose hash no longer
    matches is dropped: it was a judgement about different words."""
    return {
        iid: label
        for iid, label in labels.items()
        if iid in instances and instances[iid].output_sha256 == label.output_sha256
    }


def intra_rater_sample(
    instance_ids: Sequence[str], *, n: int = INTRA_RATER_SAMPLE, seed: int = INTRA_RATER_SEED
) -> list[str]:
    """The same hundred instances every time, chosen from the sorted ids with a fixed seed so
    the second pass cannot drift towards the easy ones."""
    ids = sorted(instance_ids)
    if len(ids) <= n:
        return ids
    rng = random.Random(seed)
    return sorted(rng.sample(ids, n))


class GoldSet(BaseModel):
    """The four files loaded together, with the cross-references checked."""

    model_config = ConfigDict(extra="forbid", frozen=True, arbitrary_types_allowed=True)

    sources: tuple[SourceDoc, ...]
    questions: tuple[GoldQuestion, ...]
    instances: tuple[AnswerInstance, ...]

    @property
    def by_source(self) -> dict[str, SourceDoc]:
        return {s.id: s for s in self.sources}

    @property
    def by_question(self) -> dict[str, GoldQuestion]:
        return {q.id: q for q in self.questions}

    @property
    def by_instance(self) -> dict[str, AnswerInstance]:
        return {i.id: i for i in self.instances}

    @property
    def arms(self) -> tuple[str, ...]:
        return tuple(sorted({i.arm_key for i in self.instances}))

    def problems(self) -> list[str]:
        """Everything wrong with the set, as a list rather than an exception, so one command
        reports all of it instead of the first."""
        out: list[str] = []
        sources, questions = self.by_source, self.by_question
        for q in self.questions:
            if q.source_id not in sources:
                out.append(f"{q.id}: source {q.source_id!r} is not in sources.jsonl")
            else:
                out.extend(f"{q.id}: {p}" for p in check_question(q, sources[q.source_id]))
        seen: set[tuple[str, str]] = set()
        for i in self.instances:
            if i.question_id not in questions:
                out.append(f"{i.id}: question {i.question_id!r} is not in questions.jsonl")
            elif questions[i.question_id].source_id != i.source_id:
                out.append(f"{i.id}: source {i.source_id!r} is not its question's source")
            if sha256_of(i.output) != i.output_sha256:
                out.append(f"{i.id}: stored hash does not match the stored text")
            key = (i.question_id, i.arm_key)
            if key in seen:
                out.append(f"{i.id}: a second answer for {key[0]} from {key[1]}")
            seen.add(key)
        by_text: dict[str, list[str]] = {}
        for src in self.sources:
            by_text.setdefault(src.text_sha256, []).append(src.id)
        for ids_sharing in by_text.values():
            if len(ids_sharing) > 1:
                # Two URLs that redirect to one page. Left in, it would put the same passage
                # under two ids, and the questions written from them would look independent
                # while resting on one document.
                out.append(f"identical passages under {', '.join(sorted(ids_sharing))}")
        for name, ids, records in (
            ("source", sources, self.sources),
            ("question", questions, self.questions),
            ("instance", self.by_instance, self.instances),
        ):
            if len(ids) != len(records):
                out.append(f"duplicate {name} ids: {len(records)} records, {len(ids)} distinct")
        return out


def normalised(text: str) -> str:
    return " ".join(text.split()).casefold()


def check_question(question: GoldQuestion, source: SourceDoc) -> list[str]:
    """A question is well written when its `must_mention` points can be checked against the
    document it names. Two failures worth catching before a single call is paid for:

    * **An answerable question whose expected points are not in the passage.** Either the
      question was written against a different page, or the passage was cut before the part
      that answers it. Either way the completeness judgement would be measuring the question
      rather than the answer.
    * **An unanswerable question whose expected point IS in the passage.** Then it is not
      unanswerable, and the one item type that catches an invented fact has been spoiled.

    Matching is literal and whitespace-insensitive, which is crude on purpose: a fuzzy match
    would pass questions this is meant to fail. A point that is genuinely a paraphrase is
    written as the phrase the document uses.
    """
    problems: list[str] = []
    haystack = normalised(source.text)
    for point in question.must_mention:
        present = normalised(point) in haystack
        if question.unanswerable and present:
            problems.append(
                f"marked unanswerable, but {point!r} is in {source.id}; it is answerable"
            )
        elif not question.unanswerable and not present:
            problems.append(f"expects {point!r}, which is not in {source.id}")
    return problems


def load(root: Path) -> GoldSet:
    return GoldSet(
        sources=tuple(read_sources(root / SOURCES_FILE)),
        questions=tuple(read_questions(root / QUESTIONS_FILE)),
        instances=tuple(read_instances(root / INSTANCES_FILE)),
    )


def summarise(gold: GoldSet, labels: Sequence[GoldLabel]) -> str:
    first = latest_labels(labels, pass_no=1)
    second = latest_labels(labels, pass_no=2)
    usable = usable_labels(first, gold.by_instance)
    lines = [
        f"sources    {len(gold.sources)}",
        f"questions  {len(gold.questions)}"
        + (
            f" ({sum(1 for q in gold.questions if q.unanswerable)} unanswerable)"
            if gold.questions
            else ""
        ),
        f"instances  {len(gold.instances)}"
        + (f" from {len(gold.arms)} models" if gold.arms else ""),
        f"labelled   {len(usable)} of {len(gold.instances)} (pass 1)",
        f"re-read    {len(second)} of {min(INTRA_RATER_SAMPLE, len(gold.instances))} (pass 2)",
    ]
    if usable:
        for task in TASKS:
            true = sum(1 for label in usable.values() if label.value(task))
            lines.append(f"  {task:9s} {true} of {len(usable)} judged true by hand")
    stale = len(first) - len(usable)
    if stale:
        lines.append(f"  {stale} label(s) dropped: the answer text no longer matches the hash")
    thin = [s.id for s in gold.sources if len(s.text) < THIN_PASSAGE_CHARS]
    if thin:
        lines.append(
            f"  thin passages, under {THIN_PASSAGE_CHARS} characters, poor material for a "
            f"faithfulness question: {', '.join(sorted(thin))}"
        )
    problems = gold.problems()
    if problems:
        lines.append("")
        lines.extend(f"PROBLEM  {p}" for p in problems)
    return "\n".join(lines)
